name: Gource Action
on:
  push:

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: 'Gource Action'
        uses: anders-kiaer/action-gource@3044016a1c6fc35a1762cc24892b581d3fabae64
        with:
          gource_seconds_per_day: 0.5
          gource_start_date: "2023-01-01"
          gource_stop_date: "2024-02-18"
          avatars_url: ./avatars
          
      - name: 'Upload gource video'
        uses: actions/upload-artifact@v2
        with:
          name: Gource
          path: ./gource/gource.mp4